version: '3.3'

services:
  bizz2goo:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3080:8000"
    volumes:
      - ./:/app
      - /var/www/html/blogStatic/:/var/www/html/blogStatic/