# Generated by Django 4.1.8 on 2025-02-13 18:25

import ckeditor.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, choices=[('Technology', 'Technology'), ('Science', 'Science'), ('Business', 'Business'), ('Entertainment', 'Entertainment'), ('Sports', 'Sports'), ('Politics', 'Politics'), ('Health', 'Health')], max_length=600, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CKPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=600)),
                ('content', ckeditor.fields.RichTextField()),
                ('slug', models.SlugField(blank=True, default='', max_length=200, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/posts')),
                ('likes', models.IntegerField(blank=True, default=0, null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='myapp.category')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=600)),
                ('email', models.EmailField(max_length=600)),
                ('subject', models.CharField(max_length=1000)),
                ('message', models.CharField(blank=True, max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=600)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='myapp.category')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postname', models.CharField(max_length=600)),
                ('category', models.CharField(max_length=600)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/posts')),
                ('content', models.CharField(max_length=100000)),
                ('time', models.CharField(blank=True, default='13 February 2025', max_length=100)),
                ('likes', models.IntegerField(blank=True, default=0, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='myapp.comment')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='myapp.ckpost')),
            ],
        ),
        migrations.AddField(
            model_name='ckpost',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.subcategory'),
        ),
        migrations.AddField(
            model_name='ckpost',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AuthorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='author_pictures/')),
                ('website', models.URLField(blank=True, null=True)),
                ('metier', models.TextField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()])),
                ('twitter', models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()])),
                ('gmail', models.EmailField(blank=True, max_length=254, null=True)),
                ('user', models.OneToOneField(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
