# Generated by Django 5.1.6 on 2025-05-15 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_advertisement_url_advertisement_external_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='category',
            field=models.ForeignKey(blank=True, help_text="Required for 'Bottom Banner Category' & optional for 'Sidebar Ad'. Specifies which category this ad is tied to.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advertisements', to='myapp.category'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='position',
            field=models.CharField(choices=[('sidebar', 'Sidebar Ad (Vertical)'), ('bottom_banner_home', 'Bottom Banner Home (Horizontal)'), ('bottom_banner_category', 'Bottom Banner Category (Horizontal)')], default='sidebar', help_text='Where this ad will be displayed.', max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.CharField(blank=True, default='15 May 2025', max_length=100),
        ),
    ]
