# Generated by Django 5.1.6 on 2025-06-18 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_advertisement_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='category',
            field=models.ForeignKey(blank=True, help_text="Required for 'Bottom Banner Category' & optional for 'Sidebar Ad'.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advertisements', to='myapp.category'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='link_type',
            field=models.CharField(choices=[('external', 'Lien Externe Personnalisé'), ('internal_form_livre', 'Formulaire Interne (Livre Création Société)'), ('internal_form_gozone', 'Formulaire Interne (Contact GOZONE)')], default='external', help_text="Choisir si l'annonce redirige vers un lien externe ou un formulaire interne.", max_length=30),
        ),
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.CharField(blank=True, default='18 June 2025', max_length=100),
        ),
    ]
