# Generated by Django 4.1.8 on 2024-11-26 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0008_authorprofile_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorprofile',
            name='metier',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='authorprofile',
            name='user',
            field=models.OneToOneField(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
