# Generated by Django 4.1.8 on 2024-11-28 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_authorprofile_metier_alter_authorprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.CharField(blank=True, default='28 November 2024', max_length=100),
        ),
    ]
