# Generated by Django 4.1.8 on 2024-11-29 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_post_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.CharField(blank=True, default='29 November 2024', max_length=100),
        ),
    ]
