# Generated by Django 4.1.8 on 2024-12-24 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_comment_parent_alter_comment_content_alter_post_time'),
        ('myapp', '0014_alter_userprofile_slug'),
    ]

    operations = [
    ]
