# Generated by Django 4.1.8 on 2024-12-24 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_merge_20241224_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorprofile',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='authorprofile',
            name='gmail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='authorprofile',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.CharField(blank=True, default='24 December 2024', max_length=100),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
