# Generated by Django 5.1 on 2024-08-26 22:02

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_comment_time_alter_post_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='CKPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
