# Generated by Django 4.1.8 on 2024-11-12 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_alter_ckpost_category_alter_ckpost_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ckpost',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='myapp.category'),
        ),
        migrations.AlterField(
            model_name='ckpost',
            name='subCategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='myapp.subcategory'),
        ),
    ]
