# Generated by Django 4.1.8 on 2024-11-12 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_alter_ckpost_category_alter_ckpost_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ckpost',
            name='subCategory',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
