# Generated by Django 4.1.8 on 2024-11-12 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_subcategory_alter_ckpost_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ckpost',
            name='subCategory',
        ),
    ]
