# Generated by Django 4.1.8 on 2024-11-13 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_ckpost_category_ckpost_sub_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ckpost',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
