# Generated by Django 4.1.8 on 2024-11-13 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_ckpost_image_ckpost_likes_ckpost_time_ckpost_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ckpost',
            old_name='time',
            new_name='updated_at',
        ),
        migrations.AddField(
            model_name='ckpost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ckpost',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ckpost',
            name='meta_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ckpost',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ckpost',
            name='share_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ckpost',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=10),
        ),
        migrations.AddField(
            model_name='ckpost',
            name='summary',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='ckpost',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='ckpost',
            unique_together={('title', 'category')},
        ),
        migrations.AddIndex(
            model_name='ckpost',
            index=models.Index(fields=['slug', 'category', 'user'], name='myapp_ckpos_slug_157d4f_idx'),
        ),
    ]
