# Generated by Django 4.1.8 on 2024-11-14 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_rename_time_ckpost_updated_at_ckpost_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ckpost',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='ckpost',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='ckpost',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='ckpost',
            name='meta_keywords',
        ),
        migrations.RemoveField(
            model_name='ckpost',
            name='share_count',
        ),
        migrations.RemoveField(
            model_name='ckpost',
            name='status',
        ),
        migrations.RemoveField(
            model_name='ckpost',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='ckpost',
            name='updated_at',
        ),
    ]
