# Generated by Django 4.1.8 on 2024-11-14 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_remove_ckpost_created_at_remove_ckpost_is_featured_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='ckpost',
            name='myapp_ckpos_slug_157d4f_idx',
        ),
        migrations.AlterUniqueTogether(
            name='ckpost',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='ckpost',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RemoveField(
            model_name='ckpost',
            name='views',
        ),
    ]
