# Generated by Django 4.1.8 on 2024-11-14 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_remove_ckpost_myapp_ckpos_slug_157d4f_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ckpost',
            name='time',
            field=models.CharField(blank=True, default='14 November 2024', max_length=100),
        ),
    ]
