# Generated by Django 4.1.8 on 2024-11-14 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0033_alter_ckpost_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ckpost',
            name='time',
        ),
    ]
