# Generated by Django 4.1.8 on 2024-11-14 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_remove_ckpost_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='ckpost',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
