# Generated by Django 4.1.8 on 2024-11-14 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0035_ckpost_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ckpost',
            name='image',
        ),
        migrations.RemoveField(
            model_name='ckpost',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='ckpost',
            name='time',
        ),
        migrations.RemoveField(
            model_name='ckpost',
            name='user',
        ),
    ]
