# Generated by Django 4.1.8 on 2024-11-14 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0037_remove_ckpost_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='ckpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/posts'),
        ),
        migrations.AddField(
            model_name='ckpost',
            name='likes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='ckpost',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='ckpost',
            name='time',
            field=models.CharField(blank=True, default='14 November 2024', max_length=100),
        ),
        migrations.AddField(
            model_name='ckpost',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
