# Generated by Django 4.1.8 on 2024-11-14 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0038_ckpost_image_ckpost_likes_ckpost_slug_ckpost_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ckpost',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
