# Generated by Django 4.1.8 on 2024-11-14 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0039_alter_ckpost_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ckpost',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
