# Generated by Django 4.1.8 on 2024-11-14 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0040_alter_ckpost_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='ckpost',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ckpost',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
