# Generated by Django 4.1.8 on 2024-11-15 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0041_ckpost_views_alter_ckpost_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ckpost',
            name='views',
        ),
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.CharField(blank=True, default='15 November 2024', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.CharField(blank=True, default='15 November 2024', max_length=100),
        ),
    ]
